# Generated by Django 3.0.7 on 2020-06-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата заполнения')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.Location', verbose_name='Спортобъект')),
            ],
        ),
    ]
