# Generated by Django 3.0.7 on 2020-06-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Спортобъект', 'verbose_name_plural': 'Спортобъекты'},
        ),
    ]
